pipeline:
  name: RAG-jith
  identifier: RAGjith
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1761129192082
        repoName: https://github.com/pidcai/rag-application-CI
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: ubuntu-gcp
                os: Linux
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.Github_OAuth_1761129192082
                    repoName: https://github.com/Royjith/rag-application-CI.git
                    build:
                      type: branch
                      spec:
                        branch: main
        delegateSelectors:
          - docker-delegate
        when:
          pipelineStatus: Success
        sendGitStatus:
          enabled: false
          name: ""
